#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require

#include "util/ray.glsl"

layout(location = 0) rayPayloadInEXT MainRay mainRay;
hitAttributeEXT vec2 attribs;

layout(set=1,binding=1) readonly buffer FaceOffsets { uint offsets[]; } blasOffsets;
#include "common/shared.hpp"
layout(set=1,binding=10) readonly buffer FaceAppearances { InstanceAppearance values[]; } instanceAppearances;
#include "common/shared.hpp"
#include "util/world_material_faces.glsl"
void main() {
    if (!acceptsWorldMaterialFace(instanceAppearances.values[blasOffsets.offsets[gl_InstanceCustomIndexEXT] + gl_GeometryIndexEXT].materialFlags, gl_HitKindEXT == gl_HitKindFrontFacingTriangleEXT, blasOffsets.offsets[gl_InstanceCustomIndexEXT] + gl_GeometryIndexEXT, gl_PrimitiveID, rayBounce(mainRay)==0u)) {
        ignoreIntersectionEXT;
        return;
    }

    if (rayInsideBoat(mainRay)) {
        ignoreIntersectionEXT;
    } else {
        return;
    }
}
