org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_loader_version=21.1.251

mod_id=radiance
mod_name=Radiance
mod_version=0.1.5-alpha
maven_group=com.radiance
archives_base_name=Radiance

create_version=6.0.10+mc1.21.1
sable_version=2.0.5+mc1.21.1
aeronautics_version=1.3.2+mc1.21.1
veil_version=4.3.2
