pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }
    }
}

rootProject.name = 'Radiance'
include ':radiance-audit'
project(':radiance-audit').projectDir = file('Modules/RadianceAudit')
