/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_FramebufferProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_FramebufferProxy
#define _Included_com_radiance_client_proxy_vulkan_FramebufferProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_proxy_vulkan_FramebufferProxy_FRAMEBUFFER
#define com_radiance_client_proxy_vulkan_FramebufferProxy_FRAMEBUFFER 36160L
#undef com_radiance_client_proxy_vulkan_FramebufferProxy_READ_FRAMEBUFFER
#define com_radiance_client_proxy_vulkan_FramebufferProxy_READ_FRAMEBUFFER 36008L
#undef com_radiance_client_proxy_vulkan_FramebufferProxy_DRAW_FRAMEBUFFER
#define com_radiance_client_proxy_vulkan_FramebufferProxy_DRAW_FRAMEBUFFER 36009L
#undef com_radiance_client_proxy_vulkan_FramebufferProxy_RENDERBUFFER
#define com_radiance_client_proxy_vulkan_FramebufferProxy_RENDERBUFFER 36161L
/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    createFramebuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_createFramebuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    deleteFramebuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_deleteFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    bindFramebuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_bindFramebuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    boundFramebuffer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_boundFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    dimensions
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_dimensions
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    checkStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_checkStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    attachTexture
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_attachTexture
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    attachRenderbuffer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_attachRenderbuffer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    createRenderbuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_createRenderbuffer
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    deleteRenderbuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_deleteRenderbuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    bindRenderbuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_bindRenderbuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    renderbufferStorage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_renderbufferStorage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    drawBuffers
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_drawBuffers
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    readBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_readBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    clear
 * Signature: (FFFFFII[I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_clear
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jintArray);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    readPixels
 * Signature: (IIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_readPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    prepareAttachmentTexture
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_prepareAttachmentTexture
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    configureMainTargetAliases
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_configureMainTargetAliases
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    defaultStencilAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_defaultStencilAvailable
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_FramebufferProxy
 * Method:    blit
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_FramebufferProxy_blit
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
