/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_ShaderProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_ShaderProxy
#define _Included_com_radiance_client_proxy_vulkan_ShaderProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_ShaderProxy
 * Method:    registerShader
 * Signature: (Ljava/lang/String;IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I[I[I[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_ShaderProxy_registerShader
  (JNIEnv *, jclass, jstring, jint, jint, jint, jstring, jstring, jstring, jstring, jint, jintArray, jintArray, jobjectArray, jobjectArray);

/*
 * Class:     com_radiance_client_proxy_vulkan_ShaderProxy
 * Method:    draw
 * Signature: (IIIIIIIJI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_ShaderProxy_draw
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
