/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_world_EntityProxy */

#ifndef _Included_com_radiance_client_proxy_world_EntityProxy
#define _Included_com_radiance_client_proxy_world_EntityProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_proxy_world_EntityProxy_DEBUG_LINE_WORLD_SCALE
#define com_radiance_client_proxy_world_EntityProxy_DEBUG_LINE_WORLD_SCALE 0.0075f
#undef com_radiance_client_proxy_world_EntityProxy_DEFAULT_LINE_WIDTH_UNITS
#define com_radiance_client_proxy_world_EntityProxy_DEFAULT_LINE_WIDTH_UNITS 2.5
#undef com_radiance_client_proxy_world_EntityProxy_DEFAULT_WORLD_LINE_WIDTH
#define com_radiance_client_proxy_world_EntityProxy_DEFAULT_WORLD_LINE_WIDTH 0.018749999f
#undef com_radiance_client_proxy_world_EntityProxy_IDENTITY_TEXT_WORLD
#define com_radiance_client_proxy_world_EntityProxy_IDENTITY_TEXT_WORLD 525836545L
#undef com_radiance_client_proxy_world_EntityProxy_IDENTITY_TEXT_PRIORITY
#define com_radiance_client_proxy_world_EntityProxy_IDENTITY_TEXT_PRIORITY 525836546L
#undef com_radiance_client_proxy_world_EntityProxy_IDENTITY_NAME_TAG_PRIORITY
#define com_radiance_client_proxy_world_EntityProxy_IDENTITY_NAME_TAG_PRIORITY 525836803L
#undef com_radiance_client_proxy_world_EntityProxy_IDENTITY_OUTLINE
#define com_radiance_client_proxy_world_EntityProxy_IDENTITY_OUTLINE 525837057L
/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    beginCachedCloud
 * Signature: (JDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_world_EntityProxy_beginCachedCloud
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    endCachedCloud
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_endCachedCloud
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    queueBuild
 * Signature: (FIZIJJJJJJJJJJJJJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_queueBuild
  (JNIEnv *, jclass, jfloat, jint, jboolean, jint, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    queueBuildSourcesV1
 * Signature: (IZFIZIJJJJJJJJJJJJJJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_queueBuildSourcesV1
  (JNIEnv *, jclass, jint, jboolean, jfloat, jint, jboolean, jint, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    beginWorldMeshFrame
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_world_EntityProxy_beginWorldMeshFrame
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    beginWorldMeshStage
 * Signature: (JJJJI)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_world_EntityProxy_beginWorldMeshStage
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    queueWorldMesh
 * Signature: (JJJJIIDDDIIIIIIIIIJIJIIFJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_world_EntityProxy_queueWorldMesh
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jdouble, jdouble, jdouble, jint, jint, jint, jint, jint, jint, jint, jint, jint, jlong, jint, jlong, jint, jint, jfloat, jlong, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    pollWorldMeshAudit
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_world_EntityProxy_pollWorldMeshAudit
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    endWorldMeshStage
 * Signature: (JJJJZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_endWorldMeshStage
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    endWorldMeshFrame
 * Signature: (JJJZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_endWorldMeshFrame
  (JNIEnv *, jclass, jlong, jlong, jlong, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    invalidateWorldMeshGeneration
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_invalidateWorldMeshGeneration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    build
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_build
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_world_EntityProxy
 * Method:    queueRigidModels
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_EntityProxy_queueRigidModels
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
