/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_RendererProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_RendererProxy
#define _Included_com_radiance_client_proxy_vulkan_RendererProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_proxy_vulkan_RendererProxy_VK_SUCCESS
#define com_radiance_client_proxy_vulkan_RendererProxy_VK_SUCCESS 0L
#undef com_radiance_client_proxy_vulkan_RendererProxy_VK_NOT_READY
#define com_radiance_client_proxy_vulkan_RendererProxy_VK_NOT_READY 1L
#undef com_radiance_client_proxy_vulkan_RendererProxy_VK_ERROR_DEVICE_LOST
#define com_radiance_client_proxy_vulkan_RendererProxy_VK_ERROR_DEVICE_LOST -4L
/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    streamlineFrameEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_streamlineFrameEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    initFolderPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_initFolderPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    initRendererNative
 * Signature: ([Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_initRendererNative
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    maxSupportedTextureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_maxSupportedTextureSize
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    capabilityLimit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_capabilityLimit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    tessellationSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_tessellationSupported
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    backendString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_backendString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    acquireContextNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_acquireContextNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    submitCommandNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_submitCommandNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    presentNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_presentNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    warmupCurrentPipelineNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_warmupCurrentPipelineNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    fuseWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_fuseWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    cameraBlockEffect
 * Signature: (IFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_cameraBlockEffect
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    cameraFluidEffect
 * Signature: (IFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_cameraFluidEffect
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    cameraFireEffect
 * Signature: (IFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_cameraFireEffect
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    postBlur
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_postBlur
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    postEntityEffect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_postEntityEffect
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    presentationRatesNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_presentationRatesNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    sectionCountsNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_sectionCountsNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    beginGpuProfile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_beginGpuProfile
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    isGpuProfileReady
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_isGpuProfileReady
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    gpuProfileTimeNs
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_gpuProfileTimeNs
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    closeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_closeNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    injectRuntimeFatalForAcceptanceNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_injectRuntimeFatalForAcceptanceNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    probeNormalCallAfterFatalNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_probeNormalCallAfterFatalNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    lifecycleAcceptanceStateNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_lifecycleAcceptanceStateNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    roundTripAcceptanceStringNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_roundTripAcceptanceStringNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    beginResourceReloadNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_beginResourceReloadNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    endResourceReloadNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_endResourceReloadNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    shouldRenderWorld
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_shouldRenderWorld
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    takeScreenshotNative
 * Signature: (ZIIIJ)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_takeScreenshotNative
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_RendererProxy
 * Method:    lastFailureDescriptionNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_client_proxy_vulkan_RendererProxy_lastFailureDescriptionNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
