/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_TextureProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_TextureProxy
#define _Included_com_radiance_client_proxy_vulkan_TextureProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_proxy_vulkan_TextureProxy_GL_TEXTURE0
#define com_radiance_client_proxy_vulkan_TextureProxy_GL_TEXTURE0 33984L
/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    generateTextureIdNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_generateTextureIdNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    releaseTextureIdNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_releaseTextureIdNative
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    prepareImageNative
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_prepareImageNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    setFilter
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_setFilter
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    isFramebufferTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_isFramebufferTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    setClamp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_setClamp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    queueUpload
 * Signature: (JIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_queueUpload
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    downloadTexture
 * Signature: (IIIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_downloadTexture
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_TextureProxy
 * Method:    uploadEmissionTileNative
 * Signature: (IJJI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_TextureProxy_uploadEmissionTileNative
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
