/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState */

#ifndef _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState
#define _Included_com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState
 * Method:    begin
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024DiagramState_begin
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState
 * Method:    post
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024DiagramState_post
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState
 * Method:    beginTarget
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024DiagramState_beginTarget
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState
 * Method:    postTarget
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024DiagramState_postTarget
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_PipelineStateProxy_DiagramState
 * Method:    abortTarget
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_PipelineStateProxy_00024DiagramState_abortTarget
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
