/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_VertexArrayProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_VertexArrayProxy
#define _Included_com_radiance_client_proxy_vulkan_VertexArrayProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    allocate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_allocate
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    release
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_release
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    defineVertexBuffer
 * Signature: (IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_defineVertexBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    defineAttribute
 * Signature: (IIIIIZZI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_defineAttribute
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    removeVertexBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_removeVertexBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    removeAttribute
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_removeAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    clearVertexBuffers
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_clearVertexBuffers
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    clearAttributes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_clearAttributes
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    defineIndexBuffer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_defineIndexBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    draw
 * Signature: (IIIIJI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_draw
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jint);

/*
 * Class:     com_radiance_client_proxy_vulkan_VertexArrayProxy
 * Method:    drawIndirect
 * Signature: (IIIJIIJI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_VertexArrayProxy_drawIndirect
  (JNIEnv *, jclass, jint, jint, jint, jlong, jint, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
