/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_world_NativeInstancingProxy */

#ifndef _Included_com_radiance_client_proxy_world_NativeInstancingProxy
#define _Included_com_radiance_client_proxy_world_NativeInstancingProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    isSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_isSupported
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    createEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    createModel
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_createModel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    uploadModelMesh
 * Signature: (JIIJIJIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_uploadModelMesh
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jint, jlong, jint, jint, jint, jint, jstring);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    finishModel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_finishModel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    deleteModel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_deleteModel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    updateInstance
 * Signature: (JJIIIZJIJJZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_updateInstance
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jboolean, jlong, jint, jlong, jlong, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    updateInstanceLighting
 * Signature: (JJIFJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_updateInstanceLighting
  (JNIEnv *, jclass, jlong, jlong, jint, jfloat, jlong);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    deleteInstance
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_deleteInstance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    beginFrame
 * Signature: (JIIID)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_beginFrame
  (JNIEnv *, jclass, jlong, jint, jint, jint, jdouble);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    setShaderLights
 * Signature: (JJIZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_setShaderLights
  (JNIEnv *, jclass, jlong, jlong, jint, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    render
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_render
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    renderCrumbling
 * Signature: (JJJJJI)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_renderCrumbling
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     com_radiance_client_proxy_world_NativeInstancingProxy
 * Method:    deleteEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_NativeInstancingProxy_deleteEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
