/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_world_ChunkProxy */

#ifndef _Included_com_radiance_client_proxy_world_ChunkProxy
#define _Included_com_radiance_client_proxy_world_ChunkProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef com_radiance_client_proxy_world_ChunkProxy_MAX_EXTERNAL_REBUILDS_PER_FRAME
#define com_radiance_client_proxy_world_ChunkProxy_MAX_EXTERNAL_REBUILDS_PER_FRAME 8L
#undef com_radiance_client_proxy_world_ChunkProxy_MIN_REBUILD_ATTEMPTS_PER_FRAME
#define com_radiance_client_proxy_world_ChunkProxy_MIN_REBUILD_ATTEMPTS_PER_FRAME 8L
#undef com_radiance_client_proxy_world_ChunkProxy_MAX_REBUILD_ATTEMPTS_PER_FRAME
#define com_radiance_client_proxy_world_ChunkProxy_MAX_REBUILD_ATTEMPTS_PER_FRAME 256L
#undef com_radiance_client_proxy_world_ChunkProxy_MIN_COLUMN_SCANS_PER_FRAME
#define com_radiance_client_proxy_world_ChunkProxy_MIN_COLUMN_SCANS_PER_FRAME 16L
#undef com_radiance_client_proxy_world_ChunkProxy_MAX_COLUMN_SCANS_PER_FRAME
#define com_radiance_client_proxy_world_ChunkProxy_MAX_COLUMN_SCANS_PER_FRAME 128L
#undef com_radiance_client_proxy_world_ChunkProxy_numImportantChunkRebuildThreads
#define com_radiance_client_proxy_world_ChunkProxy_numImportantChunkRebuildThreads 1L
/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    initNative
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_initNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    updateSectionPosNative
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_updateSectionPosNative
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    releaseSceneNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_releaseSceneNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    rebuildSingle
 * Signature: (IIIJJIJJJJJJJZIZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_rebuildSingle
  (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jint, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jboolean, jint, jboolean);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    allocateExternalChunkNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_allocateExternalChunkNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    updateExternalChunkTransformNative
 * Signature: (JDDDDDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_updateExternalChunkTransformNative
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    releaseExternalChunkNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_releaseExternalChunkNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    isChunkReady
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_isChunkReady
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    countReadyChunksNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_countReadyChunksNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    markChunkDirtyNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_markChunkDirtyNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    relocateSingle
 * Signature: (JIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_relocateSingle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlong);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    invalidateSingle
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_invalidateSingle
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    performanceSnapshotNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_performanceSnapshotNative
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_world_ChunkProxy
 * Method:    drainUpdateTraceNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_client_proxy_world_ChunkProxy_drainUpdateTraceNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
