/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_option_Options */

#ifndef _Included_com_radiance_client_option_Options
#define _Included_com_radiance_client_option_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetReflexMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetReflexMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeIsDlssFrameGenerationAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_radiance_client_option_Options_nativeIsDlssFrameGenerationAvailable
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetDlssModels
 * Signature: (IIIZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetDlssModels
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetMaxFps
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetMaxFps
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetInactivityFpsLimit
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetInactivityFpsLimit
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetVsync
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetVsync
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetChunkBuildingBatchSize
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetChunkBuildingBatchSize
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetChunkBuildingTotalBatches
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetChunkBuildingTotalBatches
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_radiance_client_option_Options
 * Method:    nativeSetCollectChunkEmission
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_option_Options_nativeSetCollectChunkEmission
  (JNIEnv *, jclass, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
