/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_client_proxy_vulkan_UiPathTracingProxy */

#ifndef _Included_com_radiance_client_proxy_vulkan_UiPathTracingProxy
#define _Included_com_radiance_client_proxy_vulkan_UiPathTracingProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_radiance_client_proxy_vulkan_UiPathTracingProxy
 * Method:    releaseScenes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_UiPathTracingProxy_releaseScenes
  (JNIEnv *, jclass);

/*
 * Class:     com_radiance_client_proxy_vulkan_UiPathTracingProxy
 * Method:    beginFrame
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_UiPathTracingProxy_beginFrame
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_radiance_client_proxy_vulkan_UiPathTracingProxy
 * Method:    endFrame
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_UiPathTracingProxy_endFrame
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_radiance_client_proxy_vulkan_UiPathTracingProxy
 * Method:    emptyView
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_UiPathTracingProxy_emptyView
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_radiance_client_proxy_vulkan_UiPathTracingProxy
 * Method:    trace
 * Signature: (JJIJIIII[Ljava/lang/String;[I[I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_client_proxy_vulkan_UiPathTracingProxy_trace
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jint, jint, jint, jobjectArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
