modLoader="javafml"
loaderVersion="[4,5)"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${homepage}"
logoFile="${logo}"
authors="${authors}"
displayTest="IGNORE_ALL_VERSION"
description='''
${description}
'''

[[mixins]]
config="radiance.mixins.json"

[[dependencies.radiance]]
modId="neoforge"
type="required"
versionRange="[${neo_loader}]"
ordering="NONE"
side="CLIENT"

[[dependencies.radiance]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="CLIENT"
