#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 5, binding = 20, rgba16f) uniform image2D volumetricLightImage;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 resolution = imageSize(volumetricLightImage);
    if (any(greaterThanEqual(pixel, resolution))) { return; }

    imageStore(volumetricLightImage, pixel, vec4(0.0));
}
