modLoader="javafml"
loaderVersion="[4,5)"
license="${license}"
issueTrackerURL="${issues}"

[[mods]]
modId="radiance_audit"
version="${version}"
displayName="${name}"
displayURL="${homepage}"
logoFile="${logo}"
authors="${authors}"
displayTest="IGNORE_ALL_VERSION"
description='''${description}'''

[[mixins]]
config="radiance-audit.mixins.json"

[[dependencies.radiance_audit]]
modId="neoforge"
type="required"
versionRange="[${neo_loader}]"
ordering="NONE"
side="CLIENT"

[[dependencies.radiance_audit]]
modId="minecraft"
type="required"
versionRange="[${minecraft}]"
ordering="NONE"
side="CLIENT"

[[dependencies.radiance_audit]]
modId="radiance"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
