file(GLOB JNI_HEADERS "${MCVR_JNI_INCLUDE_DIR}/*.h")
if(NOT JNI_HEADERS)
    message(FATAL_ERROR "No generated JNI headers found in ${MCVR_JNI_INCLUDE_DIR}")
endif()

foreach(JNI_HEADER IN LISTS JNI_HEADERS)
    get_filename_component(JNI_BASENAME "${JNI_HEADER}" NAME_WE)
    set(MIDDLEWARE_SOURCE "${MCVR_MIDDLEWARE_DIR}/${JNI_BASENAME}.cpp")
    if(JNI_BASENAME STREQUAL "com_radiance_client_proxy_vulkan_PonderProxy")
        set(MIDDLEWARE_SOURCE "${MCVR_MIDDLEWARE_DIR}/ponder_path_tracer.cpp")
    endif()
    if(NOT EXISTS "${MIDDLEWARE_SOURCE}")
        message(FATAL_ERROR "Missing middleware implementation for ${JNI_BASENAME}: ${MIDDLEWARE_SOURCE}")
    endif()

    file(READ "${JNI_HEADER}" HEADER_CONTENT)
    file(READ "${MIDDLEWARE_SOURCE}" SOURCE_CONTENT)
    string(REGEX MATCHALL "Java_[A-Za-z0-9_]+" JNI_SYMBOLS "${HEADER_CONTENT}")
    list(REMOVE_DUPLICATES JNI_SYMBOLS)
    foreach(JNI_SYMBOL IN LISTS JNI_SYMBOLS)
        string(FIND "${SOURCE_CONTENT}" "${JNI_SYMBOL}" SYMBOL_POSITION)
        if(SYMBOL_POSITION EQUAL -1)
            message(FATAL_ERROR "${MIDDLEWARE_SOURCE} does not implement ${JNI_SYMBOL}")
        endif()
    endforeach()
endforeach()
